<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Ürünler</title>
	<style>
	*{
		margin:0;
		padding:0;
		box-sizing:border-box;
	}
	body{
		font-family:Arial,Helvetica,sans-serif;
		background-color:#444;
	}
	.wrap{
		background-color:#fff;
		width:1000px;
		padding:10px;
		margin:0 auto;
	}
	.wrap:after{
		clear:both;
		content:'';
		display: table;
	}
	.product{
		width:25%;
		padding:5px;
		float:left;
	}
	.product .inner{
		cursor:pointer;
		background-color:#eee;
		border-radius:5px;
		padding:10px;
		border:1px solid #bbb;
	}
	.product .inner:hover{
		background-color:#e5e5e6
	}
	.product img {
		margin:0 auto;
		display:block
	}
	.product p{
		height:50px;
		text-align:center;
		font-size:15px;
	}
	.product h4{
		color:#bc2121;
		margin-top:5px;
	}
	.product h4 del{
		color:#999;
	}
	.product a{
		color:#444;
		text-decoration:none;
	}
	.pagination{
		margin-top:10px;
		list-style-type:none
	}
	.pagination li{
		float:left
	}
	.pagination li a{
		display:inline-block;
		padding:5px 8px;
		border:1px solid #ccc;
		color:#111;
		text-decoration:none;
	}
	.pagination li a:hover{
		background-color:#ccc;
	}
	.pagination li a.active{
		background-color:#aaa;
	}
	.clear{
		clear:both
	}
	</style>
</head>
<body>
<div class="wrap">
	<?php foreach ($products as $product): ?>
	<div class="product">
		<div class="inner">
			<a href="<?=$product['link']?>">
				<p><?=$product['name']?></p>
				<img src="<?=$product['img']?>">
				<h4><del><?=$product['oldPrice']?></del> <?=$product['price']?> ₺</h4>
			</a>
		</div>
	</div>
	<?php endforeach;?>

	<br class="clear">
	<ul class="pagination">
	<?php for ($i = 1; $i < $pageCount; $i++): ?>
		<li>
			<a <?php if ($i === (int) $page) {echo 'class="active"';}?> href="/?page=<?=$i?>"><?=$i?></a>
		</li>
	<?php endfor;?>
	</ul>
</div>
</body>
</html>
